# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '12d03d7f-9011-4de2-b31a-ab4a4d8aab8a'

  # Web app name
  webAppName: 'myflaskapp'

  # Agent VM image name
  #vmImageName: 'ubuntu-latest'

  # Environment name
  environmentName: 'dev'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  pythonVersion: '3.12.3'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      name: Default
    steps:

    - script: |
        python3 -m venv antenv
        source antenv/bin/activate
        python3 -m pip install --upgrade pip
        pip3 install setup
        pip3 install -r app/requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"

    - script: |
        echo "Removing unnecessary files to reduce package size"
        rm -rf $(projectRoot)/.git
        rm -rf $(projectRoot)/__pycache__
        rm -rf $(projectRoot)/venv
        find $(projectRoot) -name "*.pyc" -delete
      displayName: 'Clean up files'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      name: Default
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "creating deployment directory and setting permissions"
              mkdir -p /home/azureuser/dist
              sudo chown -R $USER:$USER /home/azureuser/dist
            displayName: 'Prepare deoployment directory'
          
          - script: |
              echo "Copying source code to vm location and running web app"
              rsync -av --delete \
                --exclude='.git' \
                --exclude='*.pyc' \
                --exclude='__pycache__' \
                --exclude='.venv' \
                --exclude='tests' \
                $(System.DefaultWorkingDirectory)/ /home/azureuser/dist/
            displayName: 'Copy source code to VM'

          - script: |
              echo "Installing dependencies on VM"
              cd /home/azureuser/dist
              python3 -m venv antenv
              source antenv/bin/activate
              pip3 install --upgrade pip
              pip3 install -r requirements.txt
            displayName: 'Install dependencies on VM'

          - script: |
              echo "writing systemd service file for web app"
              sudo bash -c 'cat > /etc/systemd/system/myflaskapp.service <<EOF
              [Unit]
              Description=My Flask App
              After=network.target

              [Service]
              User=azureuser
              WorkingDirectory=/home/azureuser/dist
              ExecStart=/home/azureuser/dist/antenv/bin/gunicorn app:app --bind 0.0.0.0:8080
              Restart=always

              [Install]
              WantedBy=multi-user.target
              EOF'
              displayName: 'Write systemd service file'
          
          - script: |
              echo "Reloading and resarting service..."
              sudo systemctl daemon-reload
              sudo systemctl enable myflaskapp
              sudo systemctl restart myflaskapp
              sleep 3
              sudo systemctl status myflaskapp
            displayName: 'Start/Resart Gunicorn service'
          
          - script: |
              echo "Verifying app is running..."
              curl -f http://localhost:8080 || echo "app is not responding"
            displayName: 'Check if web app is running'
            continueOnError: true
          